apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ include "java-mem-thief.name" . }}
  name: {{ include "java-mem-thief.fullname" . }}
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      targetPort: {{ .Values.service.port }}

  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "java-mem-thief.name" . }}
