apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kibana-alert-exporter
  name: kibana-alert-exporter
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      targetPort: 9101
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app: kibana-exporter