apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kibana-alert-exporter
  name: {{ include "kibana-alert-exporter.fullname" . }}
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      targetPort: {{ .Values.service.port }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kibana-alert-exporter
