{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "blackbox-operator.serviceAccountName" . }}
  labels:
    {{- include "blackbox-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "blackbox-operator.serviceAccountName" . }}-cluster-role
rules:
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["servicemonitors"]
    verbs: ["get", "list", "watch", "create", "patch"]

  - apiGroups: ["networking.istio.io"]
    resources: ["serviceentries"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "blackbox-operator.serviceAccountName" . }}-cluster-role-binding
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "blackbox-operator.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "blackbox-operator.serviceAccountName" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
